# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Welcome!
    url: /
    weight: 20
  - name: Logistics
    url: docs/
    weight: 20
   
    - name: Teaching Method & Class Policies
    url: teach/
    weight: 20
    - name: Course Technology
    url: tech/
    weight: 20
    - name: Exams & Grading
    url: exams/
    weight: 20
    
 - name: Reading Assignments
    url: read/
    weight: 20
